package main

import (
	"testing"
)

func TestMachineInit(t *testing.T) {
	// Alphabet:   ABCDEFGHIJKLMNOPQRSTUVWXYZ
	// Rotor Base1:EKMFLGDQVZNTOWYHXUSPAIBRCJ

	// Alphabet:   ABCDEFGHIJKLMNOPQRSTUVWXYZ
	// Rotor Base2:AJDKSIRUXBLHWTMCQGZNPYFVOE

	// Alphabet:   ABCDEFGHIJKLMNOPQRSTUVWXYZ
	// Rotor Base3:BDFHJLCPRTXVZNYEIWGAKMUSQO

	// Base1: EKMFLGDQVZNTOWYHXUSPAIBRCJ
	// Refl1: JCRBIAPSUXHYWOTNZVQDGLFMKE

	// Rotor Base3:BDFHJLCPRTXVZNYEIWGAKMUSQO
	// Alphabet:   ABCDEFGHIJKLMNOPQRSTUVWXYZ

	// Rotor Base2:AJDKSIRUXBLHWTMCQGZNPYFVOE
	// Alphabet:   ABCDEFGHIJKLMNOPQRSTUVWXYZ

	// Rotor Base1:EKMFLGDQVZNTOWYHXUSPAIBRCJ
	// Alphabet:   ABCDEFGHIJKLMNOPQRSTUVWXYZ
	// baseWiring1 := "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
	// baseWiring2 := "AJDKSIRUXBLHWTMCQGZNPYFVOE"
	// baseWiring3 := "BDFHJLCPRTXVZNYEIWGAKMUSQO"
	// reflBaseWiring := "EKMFLGDQVZNTOWYHXUSPAIBRCJ"

	// machine := enigma.InitMachine(baseWiring1, baseWiring2, baseWiring3, reflBaseWiring)
}
